before_script:
  - docker info

build_image:
  variables:
    IMAGE_NAME: git.fginfo.tu-bs.de:5000/fginfo/pad-archiver
  rules:
    - if: '$CI_DEFAULT_BRANCH  == $CI_COMMIT_BRANCH'
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_BRANCH .
    - docker push $IMAGE_NAME:$CI_COMMIT_BRANCH
