name: Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    name: "Checks"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v21
      with:
        nix_path: nixpkgs=channel:nixos-stable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          system-features = nixos-test benchmark big-parallel kvm
    - uses: cachix/cachix-action@v12
      with:
        name: pad-archiver
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix flake check
